<?php
/**
 * Implements hook_theme().
 */
function pds_recipe_latamvideo_theme($existing, $type, $theme, $path) {
  return [
    'pds_latamvideo' => [
      'variables' => [
        'attributes' => [],
        'heading' => NULL,
        'subheading' => NULL,
        'logo_url' => NULL,
        'link_text' => NULL,
        'link_url' => NULL,
        'thumbnail_src' => NULL,
        'thumbnail_alt' => NULL,
        'embed_html' => NULL,
      ],
      'template' => 'pds-latamvideo',
      'path' => $path . '/templates',
    ],
  ];
}
