pds_timeline.settings:
  type: config_object
  label: 'Principal: Timeline (ajustes)'
  mapping:
    header:         { type: label,  label: 'Título' }
    header_accent:  { type: label,  label: 'Título destacado' }
