name: 'PDS Country Selection'
type: site
description: 'Prepares taxonomy-ready menus and insights for country landing experiences.'
install:
  modules:
    - pds_suite
config:
  import:
    pds_suite:
      - system.menu.pds_global
      - node.type.insights
