name: 'PDS Weekly Insights'
type: site
description: 'Curates weekly digests for subscribers and newsletter feeds.'
install:
  modules:
    - pds_suite
config:
  import:
    pds_suite:
      - node.type.insights
      - node.type.market_perpectives
