pds_recipe_latamvideo.settings:
  type: config_object
  label: 'Principal: Latam video (ajustes)'
  mapping:
    header: { type: label, label: 'Título' }
    header_accent: { type: label, label: 'Título destacado' }
    description: { type: text, label: 'Descripción' }
    description_accent: { type: text, label: 'Descripción destacada' }
