name: 'PDS Motal Pageout'
type: site
description: 'Combines regulatory notices and contact journeys for modal handoffs.'
install:
  modules:
    - pds_suite
config:
  import:
    pds_suite:
      - node.type.regulatory_notices
      - system.menu.pds_footer
