name: 'PDS Market Perspective'
type: site
description: 'Builds thematic landing pages for market outlook narratives.'
install:
  modules:
    - pds_suite
config:
  import:
    pds_suite:
      - node.type.market_perpectives
      - node.type.financial_education
