name: 'PDS Timeline'
type: site
description: 'Delivers chronological storytelling using insights and market perspectives.'
install:
  modules:
    - pds_suite
config:
  import:
    pds_suite:
      - node.type.insights
      - node.type.market_perpectives
