name: 'PDS Contact Form'
type: site
description: 'Configures pathways that connect investors with support teams.'
install:
  modules:
    - pds_suite
config:
  import:
    pds_suite:
      - system.menu.pds_header
      - node.type.executives
