<?php
/**
 * Implements hook_theme().
 */
function pds_recipe_image_text_theme($existing, $type, $theme, $path) {
  return [
    'pds_recipe_image_text' => [
      'variables' => [
        'image_src' => '',
        'image_alt' => '',
        'title' => '',
        'description' => '',
        'button_url' => '',
        'button_text' => '',
        'image_position' => 'left',
      ],
      'template' => 'pds-image-text',
      'path' => $path . '/templates',
    ],
  ];
}
