pds_formas_de_invertir.settings:
  type: config_object
  label: 'Principal: Formas de Invertir (ajustes)'
  mapping:
    header:         { type: label,  label: 'Título' }
    header_accent:  { type: label,  label: 'Título destacado' }
    cards_json:    { type: text,   label: 'Tarjetas (JSON)' }
    aria_label:    { type: label,  label: 'Etiqueta ARIA' }
    prev_label:    { type: label,  label: 'Etiqueta botón anterior' }
    next_label:    { type: label,  label: 'Etiqueta botón siguiente' }