pds_suite.settings:
  type: config_object
  label: 'PDS Suite settings'
  mapping:
    api_endpoint:
      type: string
      label: 'External API endpoint'
    api_key:
      type: string
      label: 'API key'
    secret_token:
      type: string
      label: 'Secret token'
    enable_logging:
      type: boolean
      label: 'Enable API logging'
