pds_educacion_financiera.settings:
  type: config_object
  label: 'Principal: Educación financiera (ajustes)'
  mapping:
    header:        { type: label,  label: 'Título' }
    header_accent: { type: label,  label: 'Título destacado' }
    aria_label:    { type: label,  label: 'Etiqueta ARIA' }
    prev_label:    { type: label,  label: 'Etiqueta botón anterior' }
    next_label:    { type: label,  label: 'Etiqueta botón siguiente' }
    cards:
      type: sequence
      label: 'Tarjetas'
      sequence:
        type: mapping
        mapping:
          header: { type: label,  label: 'Header' }
          text:   { type: text,   label: 'Text' }
          url:    { type: string, label: 'URL' }