name: 'PDS Regulatory Notices'
type: site
description: 'Ensures compliance updates are ready for publication and syndication.'
install:
  modules:
    - pds_suite
config:
  import:
    pds_suite:
      - node.type.regulatory_notices
      - system.menu.pds_footer
