<?php
/**
 * Implements hook_theme().
 */
function pds_recipe_hero_banner_gradient_theme($existing, $type, $theme, $path) {
  //1.- Describe available variables for the hero banner gradient template.
  return [
    'pds_hero_banner_gradient' => [
      'variables' => [
        'eyebrow' => NULL,
        'headline' => NULL,
        'description' => NULL,
        'primary_button_url' => NULL,
        'primary_button_label' => NULL,
        'doc_icon_url' => NULL,
        'doc_link_url' => NULL,
        'doc_link_label' => NULL,
      ],
      'template' => 'pds-hero-banner-gradient',
      'path' => $path . '/templates',
    ],
  ];
}
