<?php
/**
 * Implements hook_theme().
 */
function pds_recipe_hero_banner_gradient_theme($existing, $type, $theme, $path) {
  return [
    'pds_hero_banner_gradient' => [
      'variables' => [
        'attributes' => [],
        'heading' => NULL,
        'subheading' => NULL,
        'logo_url' => NULL
      ],
      'template' => 'pds-hero-banner-gradient',
      'path' => $path . '/templates',
    ],
  ];
}
