name: 'PDS Ways to Invest'
type: site
description: 'Optimizes guidance pathways for various investor personas.'
install:
  modules:
    - pds_suite
config:
  import:
    pds_suite:
      - node.type.ways_to_invest
      - system.menu.pds_global
