name: 'PDS Experts Cards'
type: site
description: 'Highlights executive profiles in a reusable card layout.'
install:
  modules:
    - pds_suite
config:
  import:
    pds_suite:
      - node.type.executives
      - node.type.insights
