name: 'PDS Investment Strategies'
type: site
description: 'Activates structured investment strategy content types and menus.'
install:
  modules:
    - pds_suite
config:
  import:
    pds_suite:
      - node.type.investment_strategies
      - system.menu.pds_global
