name: 'PDS Carousel Trajectory'
type: site
description: 'Supports carousel storytelling with executive and insight highlights.'
install:
  modules:
    - pds_suite
config:
  import:
    pds_suite:
      - node.type.executives
      - node.type.insights
