<?php

/**
 * Implements hook_theme().
 */
function pds_recipe_formas_de_invertir_theme($existing, $type, $theme, $path) {
  return [
    'pds_formas_de_invertir' => [
      'template' => 'pds-formas-de-invertir',   // templates/pds-formas-de-invertir.html.twig
      'path' => $path . '/templates',
      'variables' => [
        'header' => '',
        'header_accent' => '',
        'cards' => [],        
        'aria_label' => '',
        'prev_label' => '',
        'next_label' => '',
      ],
    ],
  ];
}
