<?php
/**
 * Implements hook_theme().
 */
function pds_recipe_educacion_financiera_theme($existing, $type, $theme, $path) {
  return [
    'pds_educacion_financiera' => [
      'variables' => [
        'attributes' => [],
        'heading' => NULL,
        'subheading' => NULL,
        'logo_url' => NULL
      ],
      'template' => 'pds-educacion-financiera',
      'path' => $path . '/templates',
    ],
  ];
}
